vich_uploader:
    db_driver: orm
    mappings:
        posts:
            uri_prefix:  '%app.path.posts_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.posts_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
